version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '4000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/backend_development
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_development
